### ISSUE TITLE
How are commands with a dash handled?

### ISSUE THREAD

**Issue by ff6347** [gtg092x/node-wp-cli#8]
For example  

```
WP.core.check-update(function(err, result)
```

**Comment by ff6347** [comment]
Okay got it. They are converted to underscores.

**Comment by tdmalone** [comment]
I was wondering this too, I initially tried camelCase eg. `searchReplace` but eventually hunted through the source of node-wp-cli and found the conversion to underscore, meaning eg. `search_replace`.

Suggest mentioning this in the README. :)
